#!/usr/bin/env python3
"""Build a Markdown inventory of the maintained PRISM pipeline API surface.

The inventory is derived from ``prism.py`` and ``src/`` with Python's standard
library AST parser. Source files are read-only inputs; only the requested
Markdown output is written.
"""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CallableEntry:
    qualified_name: str
    kind: str
    line: int
    signature: str
    doc: str


@dataclass(frozen=True)
class ModuleEntry:
    path: str
    entries: tuple[CallableEntry, ...]


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    try:
        return ast.unparse(node.args)
    except (AttributeError, ValueError):
        return "..."


def _short_doc(node: ast.AST) -> str:
    doc = ast.get_docstring(node, clean=True) or ""
    return " ".join(doc.split())[:180]


def _collect_functions(body: list[ast.stmt], prefix: str = "") -> list[CallableEntry]:
    entries: list[CallableEntry] = []
    for node in body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            qualified = f"{prefix}.{node.name}" if prefix else node.name
            entries.append(CallableEntry(qualified, "function", node.lineno, _signature(node), _short_doc(node)))
            entries.extend(_collect_functions(node.body, qualified))
        elif isinstance(node, ast.ClassDef):
            qualified = f"{prefix}.{node.name}" if prefix else node.name
            entries.append(CallableEntry(qualified, "class", node.lineno, "", _short_doc(node)))
            entries.extend(_collect_functions(node.body, qualified))
    return entries


def discover_modules(root: Path) -> list[Path]:
    paths = [root / "prism.py"]
    paths.extend(sorted((root / "src").rglob("*.py")))
    return [path for path in paths if path.is_file()]


def parse_module(path: Path, root: Path) -> ModuleEntry:
    relative = path.relative_to(root).as_posix()
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=relative)
    except (OSError, SyntaxError, UnicodeDecodeError) as exc:
        entry = CallableEntry("<unparsed>", "error", 1, "", f"{type(exc).__name__}: {exc}")
        return ModuleEntry(relative, (entry,))
    return ModuleEntry(relative, tuple(_collect_functions(tree.body)))


def render(root: Path) -> str:
    modules = [parse_module(path, root) for path in discover_modules(root)]
    lines = [
        "# PRISM-prescript Maintained Function Inventory",
        "",
        "> Generated by `tools/build_pipeline_function_inventory.py`; do not edit this file by hand.",
        "> Scope: the current Python 3 entry point (`prism.py`) and maintained `src/` package.",
        "",
        "## How to use this inventory",
        "",
        "Each row gives the repository-relative file, qualified callable name, kind, source line, and signature. Private helpers are included so the inventory can detect drift; legacy `working_version/`, benchmark utilities, and tests are separate execution surfaces and are intentionally not merged into the current pipeline API.",
        "",
        "## Current file structure",
        "",
        "```text",
        "prism.py",
        "src/",
    ]
    for path in sorted(module.path for module in modules if module.path.startswith("src/")):
        lines.append(f"├── {path.removeprefix('src/')}")
    lines.extend(["```", "", "## Function and class inventory", ""])
    for module in modules:
        lines.extend([f"### `{module.path}`", ""])
        if not module.entries:
            lines.append("_No classes or functions defined in this module._")
            lines.append("")
            continue
        lines.extend([
            "| Kind | Qualified name | Line | Signature / description |",
            "| --- | --- | ---: | --- |",
        ])
        for entry in module.entries:
            signature = f"`{entry.signature}`" if entry.signature else entry.doc or "—"
            if entry.signature and entry.doc:
                signature = f"{signature} — {entry.doc}"
            escaped_signature = signature.replace("|", "\\|")
            lines.append(f"| {entry.kind} | `{entry.qualified_name}` | {entry.line} | {escaped_signature} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=None, help="Markdown output path (default: docs/PRISM_FUNCTION_INVENTORY.md)")
    args = parser.parse_args()
    root = args.root.resolve()
    output = (args.output or root / "docs/PRISM_FUNCTION_INVENTORY.md").resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(root), encoding="utf-8")
    print(f"wrote {output.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
